// <auto-generated />
namespace ITLT.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Refs_Currency_MoneyAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refs_Currency_MoneyAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201910211506432_Refs_Currency_MoneyAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
